/**
 * Fact tables for the knowledge drills.
 *
 * Everything here is checked, standard material - IANA port assignments, POSIX
 * command behaviour, RFC status codes. A generator can only be as right as its
 * table, so these are kept separate and readable rather than buried in string
 * templates. Fix a fact here and every question built from it is fixed.
 */

/** service, port, protocol, secure counterpart (if any) */
export const PORTS = [
  ['FTP data', 20, 'TCP'],
  ['FTP control', 21, 'TCP', 'FTPS (990) or SFTP (22)'],
  ['SSH (and SFTP, which runs over it)', 22, 'TCP'],
  ['Telnet', 23, 'TCP', 'SSH (22)'],
  ['SMTP', 25, 'TCP', 'SMTPS (465) or STARTTLS (587)'],
  ['DNS', 53, 'TCP and UDP'],
  ['DHCP server', 67, 'UDP'],
  ['DHCP client', 68, 'UDP'],
  ['TFTP', 69, 'UDP'],
  ['HTTP', 80, 'TCP', 'HTTPS (443)'],
  ['Kerberos', 88, 'TCP and UDP'],
  ['POP3', 110, 'TCP', 'POP3S (995)'],
  ['NTP', 123, 'UDP'],
  ['NetBIOS name service', 137, 'UDP'],
  ['NetBIOS session', 139, 'TCP'],
  ['IMAP', 143, 'TCP', 'IMAPS (993)'],
  ['SNMP', 161, 'UDP'],
  ['SNMP trap', 162, 'UDP'],
  ['LDAP', 389, 'TCP', 'LDAPS (636)'],
  ['HTTPS', 443, 'TCP'],
  ['SMB over TCP', 445, 'TCP'],
  ['SMTPS', 465, 'TCP'],
  ['Syslog', 514, 'UDP'],
  ['SMTP submission', 587, 'TCP'],
  ['LDAPS', 636, 'TCP'],
  ['IMAPS', 993, 'TCP'],
  ['POP3S', 995, 'TCP'],
  ['MSSQL', 1433, 'TCP'],
  ['Oracle DB', 1521, 'TCP'],
  ['MySQL', 3306, 'TCP'],
  ['RDP', 3389, 'TCP'],
  ['PostgreSQL', 5432, 'TCP'],
  ['VNC', 5900, 'TCP'],
  ['HTTP alternate', 8080, 'TCP'],
];

/** command, what it does, a common flag and what the flag adds */
export const LINUX = [
  ['ls', 'list the contents of a directory', '-l', 'shows a long listing with permissions, owner and size'],
  ['cd', 'change the current working directory'],
  ['pwd', 'print the full path of the working directory'],
  ['cp', 'copy files or directories', '-r', 'copies a directory and everything inside it'],
  ['mv', 'move or rename a file'],
  ['rm', 'delete a file', '-r', 'deletes a directory and its contents recursively'],
  ['mkdir', 'create a directory', '-p', 'creates parent directories as needed'],
  ['cat', 'print the whole contents of a file'],
  ['less', 'page through a file one screen at a time'],
  ['head', 'show the first lines of a file', '-n', 'sets how many lines to show'],
  ['tail', 'show the last lines of a file', '-f', 'follows the file and prints new lines as they arrive'],
  ['grep', 'search text for lines matching a pattern', '-i', 'makes the match case-insensitive'],
  ['find', 'search a directory tree for files matching criteria'],
  ['chmod', 'change the permission bits on a file'],
  ['chown', 'change the user or group that owns a file'],
  ['ps', 'list running processes', 'aux', 'lists every process on the system with its owner'],
  ['top', 'show processes and resource use, refreshing live'],
  ['kill', 'send a signal to a process by PID', '-9', 'sends SIGKILL, which cannot be caught or ignored'],
  ['df', 'report free space per mounted filesystem', '-h', 'prints sizes in human-readable units'],
  ['du', 'report how much space a directory tree uses', '-sh', 'gives one human-readable total'],
  ['tar', 'create or extract an archive', '-x', 'extracts an existing archive'],
  ['systemctl', 'control systemd services'],
  ['journalctl', 'read the systemd journal'],
  ['ip', 'show or configure network interfaces and routes'],
  ['ss', 'show open sockets and listening ports'],
  ['ping', 'test reachability with ICMP echo requests'],
  ['traceroute', 'show the hops a packet takes to a destination'],
  ['dig', 'query DNS records'],
  ['scp', 'copy files between hosts over SSH'],
  ['rsync', 'synchronise files, transferring only the differences'],
  ['sudo', 'run a command as another user, normally root'],
  ['man', 'display the manual page for a command'],
  ['script', 'record a terminal session to a file'],
  ['crontab', 'edit the schedule of recurring jobs', '-e', 'opens the current user’s crontab for editing'],
  ['uname', 'print system and kernel information', '-a', 'prints all available system information'],
  ['whoami', 'print the effective username'],
  ['awk', 'process text field by field using a pattern-action script'],
  ['sed', 'edit a stream of text with substitution rules'],
];

/** path, what lives there */
export const LINUX_PATHS = [
  ['/etc', 'system-wide configuration files'],
  ['/var/log', 'system and application log files'],
  ['/home', 'ordinary users’ home directories'],
  ['/root', 'the root user’s home directory'],
  ['/tmp', 'temporary files, usually cleared on reboot'],
  ['/usr/bin', 'the main user command binaries'],
  ['/boot', 'the kernel and bootloader files'],
  ['/dev', 'device files representing hardware'],
  ['/proc', 'a virtual filesystem exposing kernel and process state'],
  ['/opt', 'optional or third-party software packages'],
  ['/mnt', 'a mount point for temporarily mounted filesystems'],
  ['/etc/passwd', 'user account entries, without the password hashes'],
  ['/etc/shadow', 'the hashed passwords, readable only by root'],
  ['/etc/fstab', 'the filesystems to mount at boot'],
  ['/etc/hosts', 'static hostname to IP mappings checked before DNS'],
];

/** code, meaning, category */
export const HTTP_CODES = [
  [200, 'OK - the request succeeded', 'success'],
  [201, 'Created - the request succeeded and made a new resource', 'success'],
  [204, 'No Content - succeeded with nothing to return', 'success'],
  [301, 'Moved Permanently - the resource has a new permanent URL', 'redirect'],
  [302, 'Found - the resource is temporarily at a different URL', 'redirect'],
  [304, 'Not Modified - the cached copy is still valid', 'redirect'],
  [400, 'Bad Request - the server could not parse the request', 'client error'],
  [401, 'Unauthorized - authentication is required or failed', 'client error'],
  [403, 'Forbidden - authenticated but not allowed', 'client error'],
  [404, 'Not Found - no resource at that URL', 'client error'],
  [405, 'Method Not Allowed - wrong HTTP verb for this resource', 'client error'],
  [409, 'Conflict - the request clashes with the current state', 'client error'],
  [429, 'Too Many Requests - the client has been rate limited', 'client error'],
  [500, 'Internal Server Error - the server failed unexpectedly', 'server error'],
  [502, 'Bad Gateway - an upstream server returned an invalid response', 'server error'],
  [503, 'Service Unavailable - the server is overloaded or down for maintenance', 'server error'],
  [504, 'Gateway Timeout - an upstream server did not respond in time', 'server error'],
];

/** command, what it does */
export const GIT = [
  ['git clone', 'copy a remote repository, including its history, to a new local directory'],
  ['git status', 'show which files are staged, modified or untracked'],
  ['git add', 'stage changes for the next commit'],
  ['git commit', 'record the staged changes as a new commit'],
  ['git push', 'send local commits to a remote repository'],
  ['git pull', 'fetch from a remote and merge into the current branch'],
  ['git fetch', 'download remote commits without merging them'],
  ['git branch', 'list, create or delete branches'],
  ['git checkout', 'switch branches or restore files in the working tree'],
  ['git merge', 'join another branch’s history into the current one'],
  ['git rebase', 'replay commits onto a new base, rewriting their history'],
  ['git log', 'show the commit history'],
  ['git diff', 'show changes between commits, the index and the working tree'],
  ['git stash', 'set aside uncommitted changes and restore a clean working tree'],
  ['git revert', 'create a new commit that undoes an earlier one'],
  ['git reset', 'move the branch pointer, optionally changing the index and working tree'],
];

/** term, definition, field */
export const CONCEPTS = [
  // --- software development ---
  ['Idempotent operation', 'an operation that produces the same result whether applied once or many times', 'Software Development'],
  ['REST', 'an architectural style using HTTP verbs and URLs to act on stateless resources', 'Software Development'],
  ['API endpoint', 'a specific URL a client calls to reach one operation of a service', 'Software Development'],
  ['JSON', 'a text format representing structured data as objects, arrays and primitives', 'Software Development'],
  ['Big-O notation', 'a description of how an algorithm’s cost grows as the input grows', 'Software Development'],
  ['Binary search', 'an O(log n) search that repeatedly halves a sorted range', 'Software Development'],
  ['Stack', 'a last-in, first-out collection', 'Software Development'],
  ['Queue', 'a first-in, first-out collection', 'Software Development'],
  ['Hash table', 'a structure giving near constant-time lookup by key', 'Software Development'],
  ['Recursion', 'a function solving a problem by calling itself on a smaller case', 'Software Development'],
  ['Encapsulation', 'keeping an object’s internal state private and exposing behaviour instead', 'Software Development'],
  ['Inheritance', 'deriving a class from another so it reuses and extends that behaviour', 'Software Development'],
  ['Polymorphism', 'one interface serving different underlying types', 'Software Development'],
  ['Unit test', 'a test exercising one small piece of code in isolation', 'Software Development'],
  ['Integration test', 'a test exercising several components working together', 'Software Development'],
  ['CI/CD', 'automatically building, testing and releasing changes as they are merged', 'Software Development'],
  ['Version control', 'a system recording changes over time so any state can be recovered', 'Software Development'],
  ['Merge conflict', 'two branches changing the same lines, which a person must resolve', 'Software Development'],
  ['SQL JOIN', 'a clause combining rows from two tables on a related column', 'Software Development'],
  ['Primary key', 'a column whose value uniquely identifies each row in a table', 'Software Development'],
  ['Foreign key', 'a column referencing the primary key of another table', 'Software Development'],
  ['Normalisation', 'organising tables to remove redundancy and update anomalies', 'Software Development'],
  ['SQL injection', 'an attack where input is treated as SQL because it was not parameterised', 'Software Development'],
  ['Race condition', 'a defect where the result depends on the timing of concurrent work', 'Software Development'],
  ['Memory leak', 'memory that is allocated and never released, growing over time', 'Software Development'],
  ['Refactoring', 'changing a program’s structure without changing what it does', 'Software Development'],
  ['Technical debt', 'the future cost of a shortcut taken in design or implementation', 'Software Development'],
  ['Agile', 'delivering software in short iterations with feedback between them', 'Software Development'],
  ['Compiler', 'a tool translating source code into machine code ahead of running it', 'Software Development'],
  ['Interpreter', 'a tool executing source code directly, statement by statement', 'Software Development'],

  // --- cybersecurity ---
  ['Phishing', 'a message impersonating a trusted sender to obtain credentials or data', 'Cybersecurity'],
  ['Spear phishing', 'phishing aimed at one named person using details specific to them', 'Cybersecurity'],
  ['Ransomware', 'malware that encrypts data and demands payment for the key', 'Cybersecurity'],
  ['Trojan', 'malware disguised as software the user wants to install', 'Cybersecurity'],
  ['Worm', 'malware that copies itself across a network without user action', 'Cybersecurity'],
  ['Rootkit', 'malware that hides itself and other tools at a privileged level', 'Cybersecurity'],
  ['Zero-day', 'a vulnerability exploited before a patch exists', 'Cybersecurity'],
  ['Privilege escalation', 'gaining rights beyond those originally granted', 'Cybersecurity'],
  ['Least privilege', 'granting only the access a role actually requires', 'Cybersecurity'],
  ['Defence in depth', 'layering independent controls so one failure is not fatal', 'Cybersecurity'],
  ['Multi-factor authentication', 'proving identity with factors from different categories', 'Cybersecurity'],
  ['Hashing', 'a one-way transform producing a fixed-length digest of data', 'Cybersecurity'],
  ['Salting', 'adding random data before hashing so identical passwords differ', 'Cybersecurity'],
  ['Symmetric encryption', 'encryption where the same key both encrypts and decrypts', 'Cybersecurity'],
  ['Asymmetric encryption', 'encryption using a public key to encrypt and a private key to decrypt', 'Cybersecurity'],
  ['Digital signature', 'a value proving a message came from a key holder and is unaltered', 'Cybersecurity'],
  ['Certificate authority', 'a trusted body that signs certificates binding a key to an identity', 'Cybersecurity'],
  ['Man-in-the-middle', 'an attacker relaying traffic between two parties who believe they are direct', 'Cybersecurity'],
  ['DDoS', 'overwhelming a service using traffic from many distributed sources', 'Cybersecurity'],
  ['Social engineering', 'manipulating people rather than systems to gain access', 'Cybersecurity'],
  ['Penetration test', 'an authorised simulated attack to find exploitable weaknesses', 'Cybersecurity'],
  ['SIEM', 'a system aggregating and correlating security events for analysis', 'Cybersecurity'],
  ['Air gap', 'physically isolating a system from untrusted networks', 'Cybersecurity'],
  ['Data at rest', 'stored data, as opposed to data moving across a network', 'Cybersecurity'],
  ['CIA triad', 'confidentiality, integrity and availability, the three security goals', 'Cybersecurity'],
  ['Non-repudiation', 'assurance that a party cannot deny having taken an action', 'Cybersecurity'],
  ['Brute-force attack', 'trying every possible credential until one works', 'Cybersecurity'],
  ['Honeypot', 'a decoy system deployed to attract and observe attackers', 'Cybersecurity'],

  // --- emerging technologies ---
  ['Machine learning', 'systems that improve at a task by learning patterns from data', 'Emerging Technology'],
  ['Supervised learning', 'training a model on examples that are already labelled', 'Emerging Technology'],
  ['Unsupervised learning', 'finding structure in data that carries no labels', 'Emerging Technology'],
  ['Neural network', 'a model of connected weighted layers that learn representations', 'Emerging Technology'],
  ['Large language model', 'a model trained on text that predicts and generates language', 'Emerging Technology'],
  ['Training data', 'the examples a model learns from before it is used', 'Emerging Technology'],
  ['Inference', 'running a trained model to produce an output for new input', 'Emerging Technology'],
  ['Model bias', 'systematic error reflecting skew in the data a model learned from', 'Emerging Technology'],
  ['IaaS', 'cloud service supplying virtual machines, storage and networking', 'Emerging Technology'],
  ['PaaS', 'cloud service supplying a managed platform to deploy applications on', 'Emerging Technology'],
  ['SaaS', 'cloud service supplying finished applications over the network', 'Emerging Technology'],
  ['Public cloud', 'infrastructure shared between tenants and run by a provider', 'Emerging Technology'],
  ['Private cloud', 'cloud infrastructure dedicated to a single organisation', 'Emerging Technology'],
  ['Hybrid cloud', 'a deployment combining private and public cloud resources', 'Emerging Technology'],
  ['Virtualisation', 'running several isolated virtual machines on one physical host', 'Emerging Technology'],
  ['Hypervisor', 'the layer that creates and runs virtual machines', 'Emerging Technology'],
  ['Container', 'an isolated process sharing the host kernel rather than virtualising hardware', 'Emerging Technology'],
  ['Docker', 'a platform for building and running containers', 'Emerging Technology'],
  ['Kubernetes', 'a system that schedules and scales containers across many machines', 'Emerging Technology'],
  ['Microservices', 'an architecture of small independently deployable services', 'Emerging Technology'],
  ['Serverless', 'running code on demand without managing the servers underneath', 'Emerging Technology'],
  ['Edge computing', 'processing data near where it is produced instead of in a central cloud', 'Emerging Technology'],
  ['IoT', 'everyday devices with sensors and network connectivity', 'Emerging Technology'],
  ['Blockchain', 'an append-only ledger replicated across nodes and secured by hashing', 'Emerging Technology'],
  ['Smart contract', 'code on a blockchain that executes when its conditions are met', 'Emerging Technology'],
  ['Digital twin', 'a live virtual model of a physical asset used for simulation', 'Emerging Technology'],
  ['5G', 'a mobile generation offering higher throughput and lower latency than 4G', 'Emerging Technology'],
  ['Quantum computing', 'computation using qubits that can hold superposed states', 'Emerging Technology'],
  ['Zero trust', 'a model that verifies every request rather than trusting the internal network', 'Emerging Technology'],
  ['DevOps', 'practices merging development and operations to shorten delivery cycles', 'Emerging Technology'],
  ['Infrastructure as code', 'defining infrastructure in files that are versioned and applied automatically', 'Emerging Technology'],

  // --- IT general / networking ---
  ['DNS', 'the system translating domain names into IP addresses', 'Information Technology'],
  ['DHCP', 'the protocol that automatically assigns IP configuration to clients', 'Information Technology'],
  ['NAT', 'translating private addresses to a public one at the network edge', 'Networking'],
  ['VLAN', 'a logical broadcast domain separating traffic on shared switches', 'Networking'],
  ['VPN', 'an encrypted tunnel carrying private traffic across a public network', 'Networking'],
  ['Firewall', 'a control that filters traffic against a rule set', 'Networking'],
  ['Proxy server', 'an intermediary that makes requests on behalf of clients', 'Networking'],
  ['Load balancer', 'a device distributing requests across several backend servers', 'Networking'],
  ['Latency', 'the delay between sending a packet and it arriving', 'Networking'],
  ['Bandwidth', 'the maximum rate at which data can cross a link', 'Networking'],
  ['Jitter', 'variation in the delay between successive packets', 'Networking'],
  ['Packet loss', 'packets that never reach their destination', 'Networking'],
  ['MAC address', 'a hardware address identifying an interface within a local network', 'Networking'],
  ['ARP', 'the protocol resolving an IP address to a MAC address on a LAN', 'Networking'],
  ['Default gateway', 'the router a host sends traffic to when the destination is off-subnet', 'Networking'],
  ['Subnet mask', 'the value separating the network portion of an address from the host portion', 'Networking'],
  ['TCP', 'a connection-oriented transport that guarantees ordered delivery', 'Networking'],
  ['UDP', 'a connectionless transport with no delivery or ordering guarantee', 'Networking'],
  ['OSI model', 'a seven-layer reference model for network communication', 'Networking'],
  ['Switch', 'a device forwarding frames between hosts inside one local network', 'Networking'],
  ['Router', 'a device forwarding packets between different networks', 'Networking'],
  ['RAID', 'combining disks for redundancy, performance or both', 'Hardware & Operating Systems'],
  ['BIOS/UEFI', 'firmware that initialises hardware and starts the operating system', 'Hardware & Operating Systems'],
  ['Device driver', 'software letting the operating system talk to a piece of hardware', 'Hardware & Operating Systems'],
  ['Virtual memory', 'using disk space to extend apparent RAM by paging', 'Hardware & Operating Systems'],
  ['Kernel', 'the core of an operating system, managing hardware and processes', 'Hardware & Operating Systems'],
  ['Process', 'a running program with its own memory space', 'Hardware & Operating Systems'],
  ['Thread', 'a unit of execution sharing memory with others in the same process', 'Hardware & Operating Systems'],
  ['Deadlock', 'two or more processes each waiting for a resource the other holds', 'Hardware & Operating Systems'],
  ['Cache', 'fast storage holding recently or frequently used data', 'Hardware & Operating Systems'],
  ['Backup', 'a copy of data kept so it can be restored after loss', 'Information Technology'],
  ['RPO', 'the maximum data loss, in time, that a recovery plan accepts', 'Information Technology'],
  ['RTO', 'the target time within which a service must be restored', 'Information Technology'],
  ['SLA', 'an agreement defining the service level a provider commits to', 'Information Technology'],
  ['Change management', 'the controlled process for approving and recording system changes', 'Information Technology'],
  ['Incident', 'an unplanned interruption or reduction in quality of a service', 'Information Technology'],
  ['Problem', 'the underlying cause of one or more incidents', 'Information Technology'],
  ['Asset register', 'a record of the organisation’s equipment and its details', 'Information Technology'],
];
